version: '3.1'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 54333:5433
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
